POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "harsh@test.com",
  "password": "test123"
}

###
POST http://localhost:8080/api/rides/2/finalize
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXJzaEB0ZXN0LmNvbSIsImlhdCI6MTc4Njc2OTY2NCwiZXhwIjoxNzg2ODU2MDY0fQ.X_48mTr4_ADqCuZ-1gR2B6d16BEEP1Vu_nI9Ss5nn1I
Content-Type: application/json

{
  "totalFare": "150"
}